version : '3.8'

services :

  djangoapp:
    build: .
    volumes :
      - .:/home/user/src
    ports:
      - 8000:8000
      
    #Try replacing open port with expose command for containers comm
    
    
    
  # add nginx service
  
  #nginx:
    #ports : 
      #- 80:80

# ADD dockerfile for nginx
# ADD a static shared volume
